#!/bin/bash

build () {
   docker build -t gitlab_mcp -f Dockerfile .
}

run () {
#  "run",
   #        "--rm",
   #        "-i",
   #        "-e",
   #        "GITLAB_PERSONAL_ACCESS_TOKEN",
   #        "-e",
   #        "GITLAB_API_URL",
   #        "gitlab_mcp"
   docker run -it --rm gitlab_mcp

}

"$@"